---
AWSTemplateFormatVersion: 2010-09-09
Description: A sample CloudFormation template with YAML comments.

# Resources section
Resources:
  TundeVPCCreate:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Project
        - Key: Environment
          Value: Banking

